export const registerState = {
    login: '',
    password: '',
    password_again: '',
    email: '',
    first_name: '',
    last_name: '',
    birthday: '',
    captcha: '',
    role: 'Admin',
    isErrorLogin:false,
    isErrorPassword: false,
    isErrorpassword_again: false,
    isErrorEmail: false,
    isErrorfirst_name: false,
    isErrorlast_name: false,
    isErrorBirthday: false,
    isErrorCaptcha: false,
};